
CREATE TABLE IF NOT EXISTS tournois (
    id_tournoi INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    nb_matchs INT,
    nom_tournoi VARCHAR(30) NOT NULL,
    statut_ INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS equipes (
    id_equipe INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    num_equipe INT NOT NULL,
    id_tournoi INT NOT NULL,
    nom_j1 VARCHAR(30) NOT NULL,
    nom_j2 VARCHAR(30) NOT NULL,
    FOREIGN KEY (id_tournoi) REFERENCES tournois (id_tournoi) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS matchs (
    id_match INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    id_tournoi INT NOT NULL,
    num_tour INT NOT NULL,
    equipe1 INT NOT NULL,
    equipe2 INT NOT NULL,
    score1 INT DEFAULT 0,
    score2 INT DEFAULT 0,
    termine INT DEFAULT 0,
    FOREIGN KEY (id_tournoi) REFERENCES tournois (id_tournoi) ON DELETE CASCADE,
    FOREIGN KEY (equipe1) REFERENCES equipes (id_equipe),
    FOREIGN KEY (equipe2) REFERENCES equipes (id_equipe)
);